version: '3'

services:
  nginxserver:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
  
  mysqlservice:
    image: mysql:latest
    container_name: mysql_dbservice
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=somesecretpassword
      - MYSQL_DATABASE=webdatabase
      - MYSQL_USER=admin
    volumes:
      - '/home/mohit/data/mysqldatabase:/var/lib/mysql'


  